version: '3'

services:
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce:alpine
    ports:
      - published: 9000
        target: 9000
    restart: always
    volumes:
      - /usr/share/docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
