version: "3"

services:
  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
