version: '3'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: always
    volumes:
      - /usr/share/docker/adguardhome/conf:/opt/adguardhome/conf
      - /usr/share/docker/adguardhome/work:/opt/adguardhome/work
    ports:
      - '53:53'
      - '53:53/udp'
      - '3000:3000'
